<?php if( get_field('linkedin', 'option') || get_field('twitter', 'option') || get_field('facebook', 'option') || get_field('instagram', 'option') || get_field('youtube', 'option') ): ?>
<ul class="c-socials">
	<?php if( get_field('linkedin', 'option') ): ?><li><a href="<?php echo esc_url(get_field('linkedin', 'option')); ?>" target="_blank" rel="noopener" aria-label="Linkedin"><svg class="o-icon" role="presentation"><use href="<?php echo get_stylesheet_directory_uri(); ?>/build/img/icons.svg#icon-linkedin"/></svg></a><span class="u-srt">Linkedin</span></li><?php endif; ?>
	<?php if( get_field('twitter', 'option') ): ?><li><a href="<?php echo esc_url(get_field('twitter', 'option')); ?>" target="_blank" rel="noopener" aria-label="Twitter"><svg class="o-icon" role="presentation"><use href="<?php echo get_stylesheet_directory_uri(); ?>/build/img/icons.svg#icon-twitter"/></svg></a><span class="u-srt">Twitter</span></li><?php endif; ?>
	<?php if( get_field('facebook', 'option') ): ?><li><a href="<?php echo esc_url(get_field('facebook', 'option')); ?>" target="_blank" rel="noopener" aria-label="Facebook"><svg class="o-icon" role="presentation"><use href="<?php echo get_stylesheet_directory_uri(); ?>/build/img/icons.svg#icon-facebook"/></svg></a><span class="u-srt">Facebook</span></li><?php endif; ?>
	<?php if( get_field('instagram', 'option') ): ?><li><a href="<?php echo esc_url(get_field('instagram', 'option')); ?>" target="_blank" rel="noopener" aria-label="Instagram"><svg class="o-icon" role="presentation"><use href="<?php echo get_stylesheet_directory_uri(); ?>/build/img/icons.svg#icon-instagram"/></svg></a><span class="u-srt">Instagram</span></li><?php endif; ?>
	<?php if( get_field('youtube', 'option') ): ?><li><a href="<?php echo esc_url(get_field('youtube', 'option')); ?>" target="_blank" rel="noopener" aria-label="Youtube"><svg class="o-icon" role="presentation"><use href="<?php echo get_stylesheet_directory_uri(); ?>/build/img/icons.svg#icon-youtube"/></svg></a><span class="u-srt">Youtube</span></li><?php endif; ?>
</ul>
<?php endif; ?>
